sudo: required

language: node_js

services:
  - docker

before_install:
  - docker-compose -f docker-compose.test.yml build
  - docker-compose -f docker-compose.test.yml up -d users_database
  - docker-compose ps

script:
  - docker-compose -f docker-compose.test.yml up service
