sudo: required

language: node_js
node_js:
  - "6"

services:
  - docker

env:
  DOCKER_VERSION: 1.11.2
  DOCKER_COMPOSE_VERSION: 1.7.1
  DB_HOST: localhost
  DB_PORT: 28015
  SERVICE_NAME: users
  SERVICE_PORT: 80
  CONSUL_HOST: consul
  CONSUL_PORT: 8500
  PREFIXES: /users

before_install:
  - docker-compose -f ./travis/docker-compose.yml up -d
  - docker-compose -f ./travis/docker-compose.yml ps
  - cd ./service
  - npm i

script:
  - npm run test-travis
